### ISSUE TITLE
High Relevance Scores Assigned to Features with Minimal or Non-Existent Dose-Response

### ISSUE THREAD

**Issue by Pedroaragon9** [kusterlab/curve_curator#40]
Dear Flo,  
Thanks for developing CurveCurator, it's a great tool.  

I wanted to hear your opinion about curves that are assigned a high relevance score and fold change but their relative dose-response is low or non-existent.
I’ve attached an example below with two curves:
1. One showing a clear response.
2. Another with no apparent response.

Interestingly, both curves are flagged as regulated. I’ve noticed this pattern occurs for several proteins, particularly those with negative fold changes. Could you provide any insights into why these features might still be classified as regulated?

For context, some relevant parameters used below:  
```toml
['Processing'] # Parameters for the data analysis pipeline
available_cores = 4                          # Number of cores for parallel processing.
max_missing = 2                              # Number of allowed missing intensities per curve.
imputation = true                            # Whether to impute missing values.
curve_alpha = 0.05                           # <0.0, 1.0> p_value limit for a statistically meaningful curve (SAM-Analysis).
curve_fclim = 0.45                           # Absolute Log2 Fold Change limit for a biologically meaningful curve (SAM-Analysis).

['Curve Fit']
control_fold_change = true                   # <true | false> Calculate the curve fold change relative to the control.
interpolation = true                         # <true | false> Use interpolation helper points for robust curve fitting.

['F Statistic']
alpha = 0.05                                 # P-value threshold for significance.
fc_lim = 0.5                                 # Log2 Fold Change threshold.
```
Any suggestions would be really helpful, perhaps adjusting the fclim?

Thanks for the help and again, kudos for the tool it works really well.

Best, 
Pedro

![Screenshot](https://github.com/user-attachments/assets/1cfed8d6-b563-416b-83ff-b59532788d3a)
